/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 By considering the terms in the Fibonacci sequence whose values do not exceed four million (4,000,000),
 find the sum of the even-valued terms.
*/
public class Problem2 {
    public static void main(String[] ar) {

        Integer sum = 0;
        Integer prevNum = 0, currentNum = 1;
        while(prevNum < 4000000){
            prevNum += currentNum;
            currentNum += prevNum;
            if(prevNum % 2 == 0){
                sum += prevNum;
            }
            if(currentNum % 2 == 0){
                sum += currentNum;
            }
        }
        System.out.println(sum);

    }
}
